### ISSUE TITLE
Pass 'extra args' to catkin_pip_package(..) on to catkin_package()?

### ISSUE THREAD

**Issue by gavanderhoorn** [pyros-dev/catkin_pip#143]
Use-case: a Python package that also has a `CFG_EXTRAS` file to install.

`catkin_pip_package(..)` calls `catkin_package(..)` internally: https://github.com/pyros-dev/catkin_pip/blob/6c0d7599c28e3497cb649ccccd8bff7b5e125159/cmake/catkin-pip-package.cmake.in#L121
but it does not support passing any arguments to it.

For packages that are not ROS pkgs (yet), but do want to make use of the `catkin_package(.. CFG_EXTRAS ..)` functionality, there is currently no way to do that.

It would be nice if that could be supported.

**Comment by asmodehn** [comment]
Interesting... I didn't have the use-case, as the python packages I use are all independent of cmake, and while python code depends on C code, I never had the opposite (C depending on python...)

I see this as a very unlikely usage (mixing cmake and python), yet it could be an interesting point for mix-matching cmake and python (and provide close integration between build systems and cross platform scripts...)

Given that `catkin_pip_package` already make use of optional extra arguments, I think the best here is to actually add more arguments to `catkin_pip_package` itself by supporting only some of the `catkin_package` arguments.

From https://github.com/ros/catkin/blob/kinetic-devel/cmake/catkin_package.cmake I can see : 
- INCLUDE_DIRS : Not needed by python
- LIBRARIES : Managed by setup.py, so not needed here. Note here : **Even C dependencies should be managed by setup.py** to keep things simple and let python be python.
- CATKIN_DEPENDS : The final goal of this is to detect dependencies and extract include dirs and libraries. So ultimately not needed by python, unless we need to retrieve something (cmake related) from dependencies...
- DEPENDS same as catkin_depends (except find_package() call is required before)
- CFG_EXTRAS : Useful in the case where a python package wants to provide a cmake file to packages depending on it. Effectively integrating the python package into a cmake build dependency chain...
- EXPORTED_TARGETS : might be useful for eventually hooking up some setup.py commands to cmake...
- SKIP_CMAKE_CONFIG_GENERATION : could be useful
- SKIP_PKG_CONFIG_GENERATION : could be useful

Could you please comment with the options you think are useful and the ones that are not ?
Once we determine which option we can allow for catkin_pip_package, we will be able to start working towards an implementation.

**Comment by asmodehn** [comment]
Actually another option is to change the API : 
`catkin_pip_package` -> `catkin_pip_target`, since we create an actual cmake target, it would make some sense... and let the user call `catkin_package` as usual with the usual options...
It would make the cmake code simpler (which is always good).

And for the time being we can add a bwcompat `catkin_pip_package` function that does call both. (I m planning to remove it after packages using it have migrated (probably for catkin_pip 0.3).

Any preference ?

**Comment by gavanderhoorn** [comment]
My current use-case is for integrating Python-based linters that lint stuff that is not Python. Lots of those are written in Python, and converting them into a Catkin pkg is the easiest way to get them to work.

So my main interest is in `CFG_EXTRAS` at the moment.

> Actually another option is to change the API :
`catkin_pip_package` -> `catkin_pip_target`, since we create an actual cmake target, it would make some sense... and let the user call `catkin_package` as usual with the usual options...
It would make the cmake code simpler (which is always good).

yeah, that is sort of what I did (in a very hacky way: https://github.com/gavanderhoorn/catkin_pip/commit/947dd386f1261dfdc235d8a52622d671e0eca6da).

It seems to work and would address this without too much additional work.

**Comment by asmodehn** [comment]
I just committed a new version in `devel` branch that fixes this. Please try it out, and if everything is fine I ll make a new release (0.2.3) soon for (indigo, kinetic, lunar).

**Comment by gavanderhoorn** [comment]
I commented on #144.

Seems to work, but as I wrote there, really minimal testing.

**Comment by asmodehn** [comment]
This package is quite well tested, so if all tests are passing, we re good to release ;-)
Thanks for the check !

**Comment by asmodehn** [comment]
0.2.3 has been released with a fix for this. closing.
